### PR TITLE
Update main.asm

### PR DESCRIPTION
**Pull request by 6mp**
make asm version more optimized

### CODE REVIEW

**Comment by Einsight04** [comment]
LGTM! 🔥🔥🔥

**Comment by mawerty** [comment]
Hey guys i totally don't know how assembly works, is this legit or some crap that doesnt work?

**Comment by Acters** [comment]
To help with this conversation, This was discussed on StackOverflow.(Ignore the banner that says it has been answered elsewhere) https://stackoverflow.com/questions/1135679/does-using-xor-reg-reg-give-advantage-over-mov-reg-0

one user answered: "On modern CPUs the XOR pattern is preferred. It is smaller, and faster."

**Comment by JAicewizard** [comment]
Although I am not well versed with intel x86 assembly, it seems that this is indeed legit. It uses one less register and is able to save on function boilerplate

**Comment by Einsight04** [comment]
image
image

**Comment by mawerty** [comment]
Thanks! added

**Pull request merged**
