### PR TITLE
Add Malbolge support

### PR DESCRIPTION
**Pull request by skver0**

### CODE REVIEW

**Comment by hypergonial** [comment]
Damn, beat me to it.

**Comment by mawerty** [comment]
Oh my fucking god. I have just one question. WHY?

**Comment by skver0** [comment]
Have you not thought about the Malbolge userbase yet? It's quite large.

**Comment by mawerty** [comment]
Wait, why you closed the PR, I forgot to merge it ealier, and now its closed.

**Comment by skver0** [comment]
Sorry I'll make a new PR, I moved it to another branch.

**Pull request closed without merging**
